#!/usr/bin/env php
<?php

if (PHP_SAPI !== 'cli')
    die('this script must be run from CLI'.PHP_EOL);
if (PHP_SAPI === 'cli' && getcwd().DIRECTORY_SEPARATOR.'aowow' != __FILE__)
    die('this script must be run from the aowow root directory'.PHP_EOL);

// file definitions for setup
spl_autoload_register(function (string $class) : void
{
    if ($i = strrpos($class, '\\'))
        $class = substr($class, $i + 1);

    if (preg_match('/[^\w]/i', $class))
        return;

    if (file_exists('includes/setup/files/'.strtolower($class).'.class.php'))
        require_once 'includes/setup/files/'.strtolower($class).'.class.php';
    else if (file_exists('includes/setup/modelviewer/datatypes/'.strtolower($class).'.class.php'))
        require_once 'includes/setup/modelviewer/datatypes/'.strtolower($class).'.class.php';
});

require_once 'includes/kernel.php';

require_once 'setup/setup.php';

?>
