services:
  aowow:
    build:
      dockerfile: Dockerfile
      target: php-prod
      context: .
    volumes:
      # ... assume all infrastructure setup is done,
      - setup_aowow:/var/www/html/setup/mpqdata:rw  # `w` for assets download case
    env_file:
      - path: .env.aowow
        required: true
    networks:
      default:
        ipv4_address: 172.28.0.10

volumes:
  setup_aowow:
    # Contains extracted files from MPQ archives (dbc files). Required for aowow setup on initialization.
    # After setup is done, all data could be wiped, e.g. `find /usr/local/share/ -type f -delete`

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
          gateway: 172.28.0.1
