SET SESSION innodb_ft_enable_stopword = OFF;

ALTER TABLE aowow_creature
  DROP INDEX idx_name0,
  DROP INDEX idx_name2,
  DROP INDEX idx_name3,
  DROP INDEX idx_name6,
  DROP INDEX idx_name8,
  ADD INDEX idx_name0 (`name_loc0`),
  ADD INDEX idx_name2 (`name_loc2`),
  ADD INDEX idx_name3 (`name_loc3`),
  ADD INDEX idx_name4 (`name_loc4`),
  ADD INDEX idx_name6 (`name_loc6`),
  ADD INDEX idx_name8 (`name_loc8`),
  ADD FULLTEXT idx_ft_name0 (`name_loc0`),
  ADD FULLTEXT idx_ft_name2 (`name_loc2`),
  ADD FULLTEXT idx_ft_name3 (`name_loc3`),
  ADD FULLTEXT idx_ft_name6 (`name_loc6`),
  ADD FULLTEXT idx_ft_name8 (`name_loc8`);

ALTER TABLE aowow_items
  DROP INDEX idx_name0,
  DROP INDEX idx_name2,
  DROP INDEX idx_name3,
  DROP INDEX idx_name6,
  DROP INDEX idx_name8,
  ADD INDEX idx_name0 (`name_loc0`),
  ADD INDEX idx_name2 (`name_loc2`),
  ADD INDEX idx_name3 (`name_loc3`),
  ADD INDEX idx_name4 (`name_loc4`),
  ADD INDEX idx_name6 (`name_loc6`),
  ADD INDEX idx_name8 (`name_loc8`),
  ADD FULLTEXT idx_ft_name0 (`name_loc0`),
  ADD FULLTEXT idx_ft_name2 (`name_loc2`),
  ADD FULLTEXT idx_ft_name3 (`name_loc3`),
  ADD FULLTEXT idx_ft_name6 (`name_loc6`),
  ADD FULLTEXT idx_ft_name8 (`name_loc8`);

ALTER TABLE aowow_objects
  DROP INDEX idx_name0,
  DROP INDEX idx_name2,
  DROP INDEX idx_name3,
  DROP INDEX idx_name6,
  DROP INDEX idx_name8,
  ADD INDEX idx_name0 (`name_loc0`),
  ADD INDEX idx_name2 (`name_loc2`),
  ADD INDEX idx_name3 (`name_loc3`),
  ADD INDEX idx_name4 (`name_loc4`),
  ADD INDEX idx_name6 (`name_loc6`),
  ADD INDEX idx_name8 (`name_loc8`),
  ADD FULLTEXT idx_ft_name0 (`name_loc0`),
  ADD FULLTEXT idx_ft_name2 (`name_loc2`),
  ADD FULLTEXT idx_ft_name3 (`name_loc3`),
  ADD FULLTEXT idx_ft_name6 (`name_loc6`),
  ADD FULLTEXT idx_ft_name8 (`name_loc8`);

ALTER TABLE aowow_quests
  DROP INDEX idx_name0,
  DROP INDEX idx_name2,
  DROP INDEX idx_name3,
  DROP INDEX idx_name6,
  DROP INDEX idx_name8,
  ADD INDEX idx_name0 (`name_loc0`),
  ADD INDEX idx_name2 (`name_loc2`),
  ADD INDEX idx_name3 (`name_loc3`),
  ADD INDEX idx_name4 (`name_loc4`),
  ADD INDEX idx_name6 (`name_loc6`),
  ADD INDEX idx_name8 (`name_loc8`),
  ADD FULLTEXT idx_ft_name0 (`name_loc0`),
  ADD FULLTEXT idx_ft_name2 (`name_loc2`),
  ADD FULLTEXT idx_ft_name3 (`name_loc3`),
  ADD FULLTEXT idx_ft_name6 (`name_loc6`),
  ADD FULLTEXT idx_ft_name8 (`name_loc8`);

ALTER TABLE aowow_spell
  DROP INDEX idx_name0,
  DROP INDEX idx_name2,
  DROP INDEX idx_name3,
  DROP INDEX idx_name6,
  DROP INDEX idx_name8,
  ADD INDEX idx_name0 (`name_loc0`),
  ADD INDEX idx_name2 (`name_loc2`),
  ADD INDEX idx_name3 (`name_loc3`),
  ADD INDEX idx_name4 (`name_loc4`),
  ADD INDEX idx_name6 (`name_loc6`),
  ADD INDEX idx_name8 (`name_loc8`),
  ADD FULLTEXT idx_ft_name0 (`name_loc0`),
  ADD FULLTEXT idx_ft_name2 (`name_loc2`),
  ADD FULLTEXT idx_ft_name3 (`name_loc3`),
  ADD FULLTEXT idx_ft_name6 (`name_loc6`),
  ADD FULLTEXT idx_ft_name8 (`name_loc8`);
