DROP TABLE IF EXISTS `aowow_seo_descriptions`;
CREATE TABLE `aowow_seo_descriptions` (
  `page` varchar(255) NOT NULL,
  `locale` tinyint(3) NOT NULL,
  `description` text NOT NULL,
  `comment` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`page`, `locale`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `aowow_seo_descriptions` VALUES
    ('maps', 0, 'Maps of all zones with support for pins and coordinates display, with options for sharing.', null),
    ('maps', 2, 'Des cartes de toutes les zones avec le support des marqueurs et des coordonnées, plus des options pour partager le contenu.', null),
    ('maps', 3, 'Karten aller Gebiete. Unterstützt Markierungen und Koordinaten. Karten können weitergegeben werden.', null),
    ('maps', 4, '所有区域地图，支持标记和坐标显示，并提供分享选项。', 'automated translation'),
    ('maps', 6, 'Mapas de todas las zonas con soporte para marcadores y visualización de coordenadas, con opciones para compartir.', null),
    ('maps', 8, 'Карты всех локаций, с поддержкой маркеров и отображением координат, с возможностью поделиться.', null),

    ('search', 0, 'The largest World of Warcraft (WoW) information website, featuring information on classes, professions, raids, and more.', null),
    ('search', 2, 'Le plus grand site d''information sur World of Warcraft (WoW), proposant des informations sur les classes, professions, raids, et plus.', null),
    ('search', 3, 'Die größte World of Warcraft (WoW) Datenbank mit News, Guides, Talentrechner, Gegenständen, Quests, Profilen und noch viel mehr.', null),
    ('search', 4, '最大的魔兽世界（WoW）资讯网站，数据库、职业讲解、攻略、专业技能、团本、成就。', null),
    ('search', 6, 'La mayor web de información sobre World of Warcraft (WoW), con información sobre clases, profesiones, bandas y mucho más!', null),
    ('search', 8, 'Крупнейший сайт с информацией о World of Warcraft (WoW). Здесь вы найдете руководства и узнаете все подробности, касающиеся профессий, классов, рейдов и многом другом.', null),

    ('petcalc', 0, 'Hunter Pet Talent Calculator for World of Warcraft. Cunning, Tenacity and Ferocity.', null),
    ('petcalc', 2, 'Calculateur de talents de familiers pour Wrath of the Lich King. Ruse, Ténacité et Férocité.', null),
    ('petcalc', 3, 'Begleiterrechner für Wrath of the Lich King. List, Hartnäckigkeit und Wildheit.', null),
    ('petcalc', 4, '魔兽世界猎手宠物天赋模拟器。狡诈、坚韧、狂野。', null),
    ('petcalc', 6, 'Calculadora de talentos de Mascotas de Cazadores para World of Warcraft. Astucia, Tenacidad y Ferocidad.', null),
    ('petcalc', 8, 'Калькулятор талантов питомцев для World of Warcraft. Хитрость, Упорство, Свирепость.', null),

    ('talent', 0, 'Talent Calculator for Wrath of the Lich King. Theorycraft, plan, and share your WotLK character builds for all ten classes.', null),
    ('talent', 2, 'Calculateur de talents pour Wrath of the Lich King : préparez et partagez vos configurations de personnage pour les dix classes !', null),
    ('talent', 3, 'Talentrechner für Wrath of the Lich King Classic. Theorycraftet, plant und teilt eure Charakterbuilds für alle zehn Klassen.', null),
    ('talent', 4, '巫妖王之怒天赋模拟器。为所有十个职业进行理论构筑、规划并分享你的巫妖王之怒角色配置。', 'automated translation'),
    ('talent', 6, 'Calculadora de Talentos para Wrath of the Lich King. Planea, teoriza y comparte tus configuraciones de personaje para las 10 clases.', null),
    ('talent', 8, 'Калькулятор талантов Wrath of the Lich King. Создавайте и делитесь билдами классических персонажей всех десяти классов.', null),

    ('compare', 0, 'Add items or item sets to a table to compare stats, including support for stat weights.', null),
    ('compare', 2, 'Ajouter des objets ou des ensembles d''objets à une table pour comparer leurs statistiques, avec le support des balances de statistiques.', null),
    ('compare', 3, 'Füge Gegenstände oder Ausrüstungssets der Tabelle hinzu um ihre Werte zu gewichten und vergleichen.', null),
    ('compare', 4, '将物品或物品套装添加到表格中以比较属性，并支持属性权重。', 'automated translation'),
    ('compare', 6, 'Añade objetos o conjuntos de objetos a una taba para comparar sus estadísticas, incluyendo soporte para valores de estadísticas.', null),
    ('compare', 8, 'Добавляйте предметы или комплекты, чтобы сравнить их характеристики. Поддерживает функцию значимости характеристик.', null),

    ('sound&playlist', 0, 'Here you can set up a playlist of sounds and music.', null),
    ('sound&playlist', 2, 'Ici, vous pouvez créer une liste de lecture de sons et de musique.', 'automated translation'),
    ('sound&playlist', 3, 'Hier könnt ihr eine Playlist aus Klängen und Musik zusammenstellen.', null),
    ('sound&playlist', 4, '在这里，您可以设置声音和音乐播放列表。', 'automated translation'),
    ('sound&playlist', 6, 'Aquí puedes configurar una lista de reproducción de sonidos y música.', null),
    ('sound&playlist', 8, 'Здесь вы можете создать плейлист из звуков и музыки.', 'automated translation'),

    ('latest-comments', 0, 'The latest comments on our World of Warcraft database pages.', null),
    ('latest-comments', 2, 'Les derniers commentaires postés sur les pages de notre base de données World of Warcraft.', null),
    ('latest-comments', 3, 'Die neuesten Kommentare zu unseren World of Warcraft Datenbankseiten.', null),
    ('latest-comments', 4, '我们《魔兽世界》数据库页面上的最新评论。', 'automated translation'),
    ('latest-comments', 6, 'Los comentarios más recientes en nuestras páginas de base de datos de World of Warcraft.', null),
    ('latest-comments', 8, 'Самые свежие комментарии со страниц базы данных World of Warcraft.', null),

    ('latest-screenshots', 0, 'The latest screenshots added to our World of Warcraft database.', null),
    ('latest-screenshots', 2, 'Les dernières captures d''écran ajoutées à notre base de données World of Warcraft.', null),
    ('latest-screenshots', 3, 'Die neuesten Screenshots, die der World of Warcraft Datenbank hinzugefügt wurden.', null),
    ('latest-screenshots', 4, '添加到我们《魔兽世界》数据库中的最新截图。', 'automated translation'),
    ('latest-screenshots', 6, 'Las capturas de pantalla agregadas más recientemente a nuestra base de datos de Wowhead.', null),
    ('latest-screenshots', 8, 'Последние скриншоты, добавленные в базу данных World of Warcraft.', null),

    ('latest-videos', 0, 'The latest videos added to our World of Warcraft database.', null),
    ('latest-videos', 2, 'Les dernières vidéos ajoutées à notre base de données World of Warcraft.', null),
    ('latest-videos', 3, 'Die neuesten Videos, die der World of Warcraft Datenbank hinzugefügt wurden.', null),
    ('latest-videos', 4, '添加到我们《魔兽世界》数据库中的最新视频。', 'automated translation'),
    ('latest-videos', 6, 'Los videos agregados más recientemente a nuestra base de datos de World of Warcraft.', null),
    ('latest-videos', 8, 'Последние видео, добавленные в базу данных World of Warcraft.', null),

    ('missing-screenshots', 0, 'Database pages that are missing screenshots, but have at least 1 comment.', null),
    ('missing-screenshots', 2, 'Pages de base de données qui n''ont pas de captures d''écran, mais qui ont au moins 1 commentaire.', 'automated translation'),
    ('missing-screenshots', 3, 'Datenbankseiten ohne Screenshots, aber mit mindestens einem Kommentar.', 'automated translation'),
    ('missing-screenshots', 4, '缺少截图但至少有 1 条评论的数据库页面。', 'automated translation'),
    ('missing-screenshots', 6, 'Páginas de la base de datos que no tienen capturas de pantalla, pero tienen al menos 1 comentario.', 'automated translation'),
    ('missing-screenshots', 8, 'Страницы базы данных без скриншотов, но имеющие, по крайней мере, 1 комментарий.', null),

    ('most-comments', 0, 'Database pages with the most comments yesterday.', null),
    ('most-comments', 2, 'Pages de base de données avec le plus de commentaires hier.', 'automated translation'),
    ('most-comments', 3, 'Datenbankseiten mit den meisten Kommentaren gestern.', 'automated translation'),
    ('most-comments', 4, '昨天评论最多的数据库页面。', 'automated translation'),
    ('most-comments', 6, 'Páginas de la base de datos con más comentarios ayer.', 'automated translation'),
    ('most-comments', 8, 'Страницы базы данных с наибольшим количеством комментариев вчера.', 'automated translation'),

    ('most-comments=7', 0, 'Database pages with the most comments in the past 7 days.', null),
    ('most-comments=7', 2, 'Pages de base de données avec le plus de commentaires au cours des 7 derniers jours.', 'automated translation'),
    ('most-comments=7', 3, 'Datenbankseiten mit den meisten Kommentaren in den letzten 7 Tagen.', 'automated translation'),
    ('most-comments=7', 4, '过去 7 天评论最多的数据库页面。', 'automated translation'),
    ('most-comments=7', 6, 'Páginas de la base de datos con más comentarios en los últimos 7 días.', 'automated translation'),
    ('most-comments=7', 8, 'Самые обсуждаемые страницы базы данных за последние 7 дней.', null),

    ('most-comments=30', 0, 'Database pages with the most comments in the past 30 days.', null),
    ('most-comments=30', 2, 'Pages de base de données avec le plus de commentaires au cours des 30 derniers jours.', 'automated translation'),
    ('most-comments=30', 3, 'Datenbankseiten mit den meisten Kommentaren in den letzten 30 Tagen.', 'automated translation'),
    ('most-comments=30', 4, '过去 30 天评论最多的数据库页面。', 'automated translation'),
    ('most-comments=30', 6, 'Páginas de la base de datos con más comentarios en los últimos 30 días.', 'automated translation'),
    ('most-comments=30', 8, 'Самые обсуждаемые страницы базы данных за последние 30 дней.', null),

    ('unrated-comments', 0, 'Database comments that haven''t yet been rated by our users.', null),
    ('unrated-comments', 2, 'Commentaires de base de données qui n''ont pas encore été évalués par nos utilisateurs.', 'automated translation'),
    ('unrated-comments', 3, 'Datenbank-Kommentare, die noch nicht von unseren Benutzern bewertet wurden.', null),
    ('unrated-comments', 4, '尚未被我们的用户评分的数据库评论。', 'automated translation'),
    ('unrated-comments', 6, 'Comentarios de la base de datos que aún no han sido calificados por nuestros usuarios.', 'automated translation'),
    ('unrated-comments', 8, 'Комментарии в базе данных, которые пока не были оценены нашими пользователями.', null),

    ('profiler', 0, 'Load your character''s Blizzard Battle.net profile or create a custom list.', null),
    ('profiler', 2, 'Charger le profil de votre personnage sur Blizzard Battle.net, ou créer une liste personnalisée.', null),
    ('profiler', 3, 'Lade das Battle.net-Profil deines Charakters oder erstelle eine benutzerdefinierte Liste.', null),
    ('profiler', 4, '加载你角色的暴雪 Battle.net 资料，或创建自定义列表。', 'automated translation'),
    ('profiler', 6, 'Carga el perfil de Battle.net de tu personaje o crea una lista personalizada.', null),
    ('profiler', 8, 'Загрузите профиль вашего персонажа из Blizzard Battle.net или создайте свой список.', null),

    ('profile&new', 0, 'Try out armor sets on any World of Warcraft character. Test different transmog and plan your wardrobe.', null),
    ('profile&new', 2, 'Essayez des sets d''armure sur n''importe quel personnage de World of Warcraft. Essayez différentes transmogrifications et planifiée votre garde-robe.', null),
    ('profile&new', 3, 'Probieren Sie Rüstungssets an jedem World of Warcraft Charakter an. Testen Sie verschiedene Transmogs und planen Sie ihre Garderobe.', null),
    ('profile&new', 4, '在任意《魔兽世界》角色上试穿护甲套装。测试不同幻化并规划你的衣柜。', 'automated translation'),
    ('profile&new', 6, 'Prueba conjuntos de armadura en cualquier personaje de World of Warcraft. Prueba diferentes transfiguraciones y prepara tu armario.', null),
    ('profile&new', 8, 'Примерьте доспехи на любого персонажа. Поиграйтесь с трансмогрификацией и продумайте внешний вид.', null),

    ('privileges', 0, 'All the site privileges earned through AoWoW''s reputation system.', null),

    ('item=47241', 0, 'This currency can be used to purchase item level 245 epic quality gear, item level 232 PVP gear, and Tier 9+ tokens from vendors found throughout Dalaran.', 'valid detail page example'),
    ('item=47241', 2, 'Cette devise peut être utilisée pour acheter des équipements épiques de niveau 245, des équipements JcJ de niveau 232 et des jetons de niveau Tier 9+ auprès de vendeurs présents dans Dalaran.', 'automated translation'),
    ('item=47241', 3, 'Diese Währung kann verwendet werden, um Gegenstände der Stufe 245 mit epischer Qualität, PvP-Gegenstände der Stufe 232 und Tier-9+-Token bei Händlern in Dalaran zu erwerben.', 'automated translation'),
    ('item=47241', 4, '这种货币可用于从达拉然各处的商人处购买 245 级史诗品质装备、232 级 PVP 装备以及 9 阶及以上的代币。', 'automated translation'),
    ('item=47241', 6, 'Esta divisa puede usarse para comprar equipo épico de nivel 245, equipo JcJ de nivel 232 y fichas de rango Tier 9+ a vendedores repartidos por Dalaran.', 'automated translation'),
    ('item=47241', 8, 'Эту валюту можно использовать для покупки эпических предметов уровня 245, PvP-предметов уровня 232 и жетонов Tier 9+ у продавцов по всему Даларану.', 'automated translation'),

    ('item=49426', 0, 'This currency can be used to purchase item level 264 epic quality gear, item level 251 PVP gear, and Tier 10+ tokens from vendors found throughout Dalaran.', 'valid detail page example'),
    ('item=49426', 2, 'Cette devise peut être utilisée pour acheter des équipements épiques de niveau 264, des équipements JcJ de niveau 251 et des jetons de niveau Tier 10+ auprès de vendeurs présents dans Dalaran.', 'automated translation'),
    ('item=49426', 3, 'Diese Währung kann verwendet werden, um Gegenstände der Stufe 264 mit epischer Qualität, PvP-Gegenstände der Stufe 251 und Tier-10+-Token bei Händlern in Dalaran zu erwerben.', 'automated translation'),
    ('item=49426', 4, '这种货币可用于从达拉然各处的商人处购买 264 级史诗品质装备、251 级 PVP 装备以及 10 阶及以上的代币。', 'automated translation'),
    ('item=49426', 6, 'Esta divisa puede usarse para comprar equipo épico de nivel 264, equipo JcJ de nivel 251 y fichas de rango Tier 10+ a vendedores repartidos por Dalaran.', 'automated translation'),
    ('item=49426', 8, 'Эту валюту можно использовать для покупки эпических предметов уровня 264, PvP-предметов уровня 251 и жетонов Tier 10+ у продавцов по всему Даларану.', 'automated translation'),

    ('faq', 0, 'Can''t find the answer you were looking for? Just contact us, or post on our forums!', null),
    ('faq', 2, 'Vous ne trouvez pas la réponse que vous cherchiez ? Contactez-nous simplement, ou publiez sur nos forums !', 'automated translation'),
    ('faq', 3, 'Könnt ihr die gesuchte Antwort nicht finden? Kontaktieren Sie uns einfach oder postet in unseren Foren!', 'automated translation'),
    ('faq', 4, '找不到您想要的答案？只需联系我们，或在我们的论坛上发帖！', 'automated translation'),
    ('faq', 6, '¿No encuentras la respuesta que estabas buscando? ¡Ponte en contacto con nosotros o publica en nuestros foros!', 'automated translation'),
    ('faq', 8, 'Не нашли нужный ответ? Просто свяжитесь с нами или оставьте сообщение на наших форумах!', 'automated translation')
;
