<?php

namespace Aowow;

if (!defined('AOWOW_REVISION'))
    die('illegal access');


// page is generated by jScript .. does this need to be here then..?
class ProfileSummaryResponse extends TextResponse
{
    public function __construct() {}

    protected function generate() : void {}
}

?>
