{strip}
    us_addCharactersTab([
        {ldelim}
            id:763,
            "name":"Lilywhite",
            "achievementpoints":"0",
            "guild":"whatever",
            "guildrank":"0",
            "realm":"draenor",
            "realmname":"Draenor",
            "battlegroup":"cyclone",
            "battlegroupname":"Cyclone",
            "region":"us",
            "level":"10",
            "race":"7",
            "gender":"0",
            "classs":"1",
            "faction":"0",
            "gearscore":"0",
            "talenttree1":"0",
            "talenttree2":"0",
            "talenttree3":"0",
            "talentspec":0,
            "published":1,
            "pinned":0
        {rdelim}
    ]);
{/strip}