<?php

namespace Aowow;

if (!defined('AOWOW_REVISION'))
    die("illegal access");


interface ITooltip
{
    public function renderTooltip() : ?string;
}

interface ISource
{
    public function getRawSource(int $src) : array;
    public function getSources() : ?array;
    public function getSourceData(/* int $id = 0 */) : array;
    public function hasAnySource() : bool;
}

/* source more: keys seen used
     'n':   name [always set]
     't':   type [always set]
    'ti':   typeId [always set]
    'bd':   BossDrop [0; 1] [Creature / GO]
    'dd':   DungeonDifficulty [-2: DungeonHC; -1: DungeonNM; 1: Raid10NM; 2:Raid25NM; 3:Raid10HM; 4: Raid25HM; 99: filler trash] [Creature / GO]
     'q':   cssQuality [Items]
     'z':   zone [set when everything happens in one zone]
     'p':   PvP [pvpSourceId]
     's':   Type::TITLE: side; Type::SPELL: skillId (yeah, conflicting use cases. Ain't life just grand.)
     'c':   category [Spells / Quests]
    'c2':   subCat [Quests]
  'icon':   iconString
*/
trait TrSourceHelper
{
    public readonly  array $sources;
    public readonly ?int   $moreType;
    public readonly ?int   $moreTypeId;
    public readonly ?int   $moreZoneId;
    public readonly ?int   $moreMask;                       // srcFlags

    // the result for js
    private ?array $source     = null;
    private ?array $sourceMore = null;

    private function initSources(array $initData) : void
    {
        $src = [];
        for ($i = SRC_CRAFTED; $i < MAX_SOURCES; $i++)
            $src[$i][] = $initData['src'.$i] ?: null;

        $this->sources = $src;
    }

    public function getRawSource(int $src) : array
    {
        return $this->sources[$src] ?? [];
    }

    public function hasAnySource() : bool
    {
        return !!array_filter($this->sources);
    }

    public function prepareSourceMore(?DBType $src = null) : void
    {
        if (!$this->sourceMore !== null || !($this instanceof DBType))
            return;

        // not provided by external bulk operation
        if (!$src && $this->moreType && $this->moreTypeId)
            $src = Type::newType($this->moreType, $this->moreTypeId);

        if ($src && $src instanceof ISource && $src->id == $this->id)
            $this->sourceMore = $src->getSourceData();
        else
            $this->sourceMore = [];
    }

    public function getSources() : ?array
    {
        if (empty($this->sources))
            return null;

        if ($this->sourceMore === null)
            $this->prepareSourceMore();

        $s  = array_keys($this->sources);
        $sm = [];

        if ($_ = $this->sourceMore)
            $sm = $_;

        if ($p = $this->sources[SRC_PVP])
            $sm['p'] = $p[0];

        if ($z = $this->moreZoneId)
            $sm['z'] = $z;

        if ($this->moreMask & SRC_FLAG_BOSSDROP)
            $sm['bd'] = 1;

        if ($this->sources[SRC_DROP])
        {
            /*
                mode        srcFlag     log2    dd Flag
                10N/D-NH    0b0001      0       0b001
                25N/D-HC    0b0010      1       0b010
                10H         0b0100      2       0b011
                25H         0b1000      3       0b100
            */
            if ($this->moreMask & SRC_FLAG_COMMON)
                $sm['dd'] = 99;
            else if ($this->moreMask & SRC_FLAG_DUNGEON_DROP)
                $sm['dd'] = $this->sources[SRC_DROP][0] * -1;
            else if ($this->moreMask & SRC_FLAG_RAID_DROP)
            {
                $dd = log($this->sources[SRC_DROP][0], 2);
                if ($dd == intVal($dd))                     // only one bit set
                    $sm['dd'] = $dd + 1;
            }
        }

        return [$s, $sm ? [$sm] : []];
    }
}

interface IListview
{
    // should return data required to display an arbitrary listview
    public function getListviewData() : array;
    // test if a property is in use
    public function hasSetFields(?string ...$fields) : int;
    // test if a property is in use and different between rows
    public function hasDiffFields(?string ...$fields) : int;
}


/*
    !IMPORTANT!
    It is flat out impossible to distinguish between floors for multi-level areas, if the floors overlap each other!
    The coordinates generated by the script WILL be on every level and will have to be removed MANUALLY!

    impossible := you are not keen on reading wmo data and match it to DungeonMapChunk.dbc;
*/
trait TrSpawnHelper
{
    private array $spawnResult = array(
        SPAWNINFO_FULL  => null,
        SPAWNINFO_SHORT => null,
        SPAWNINFO_ZONES => null,
        SPAWNINFO_QUEST => null
    );

    private function createShortSpawns() : void             // [zoneId, floor, [[x1, y1], [x2, y2], ..]] as tooltip2 if enabled by <a rel="map" ...> or anchor #map (one area, one floor, one creature, no survivors)
    {
        $this->spawnResult[SPAWNINFO_SHORT] = new \StdClass;

        // first get zone/floor with the most spawns
        if ($res = DB::Aowow()->selectRow('SELECT `areaId`, `floor` FROM ::spawns WHERE `type` = %i AND `typeId` = %i AND `posX` > 0 AND `posY` > 0 GROUP BY `areaId`, `floor` ORDER BY COUNT(1) DESC LIMIT 1', self::$dbType, $this->id))
        {
            // get relevant spawn points
            $points = DB::Aowow()->selectAssoc('SELECT `posX`, `posY` FROM ::spawns WHERE `type` = %i AND `typeId` = %i AND `areaId` = %i AND `floor` = %i AND `posX` > 0 AND `posY` > 0', self::$dbType, $this->id, $res['areaId'], $res['floor']);
            $spawns = [];
            foreach ($points as $p)
                $spawns[] = [$p['posX'], $p['posY']];

            $this->spawnResult[SPAWNINFO_SHORT]->zone   = $res['areaId'];
            $this->spawnResult[SPAWNINFO_SHORT]->coords = [$res['floor'] => $spawns];
        }
    }

    // for display on map (object/npc detail page)
    private function createFullSpawns(bool $skipWPs = false, bool $skipAdmin = false, bool $hasLabel = false, bool $hasLink = false) : void
    {
        $data     = [];
        $wpSum    = [];
        $wpIdx    = 0;
        $worldPos = [];
        $spawns   = DB::Aowow()->selectAssoc(
           'SELECT CASE WHEN z.`type` = %i THEN 1
                        WHEN z.`type` = %i THEN 2
                        WHEN z.`type` = %i THEN 2
                        ELSE 0
                   END AS "mapType", s.*
            FROM   ::spawns s
            JOIN   ::zones z ON s.areaId = z.id
            WHERE s.`type` = %i AND s.`typeId` IN %in AND s.`posX` > 0 AND s.`posY` > 0',
            MAP_TYPE_DUNGEON_HC, MAP_TYPE_MMODE_RAID, MAP_TYPE_MMODE_RAID_HC,
            self::$dbType, $this->getFoundIDs()
        ) ?: [];

        if (!$skipAdmin && User::isInGroup(U_GROUP_MODERATOR))
            if ($guids = array_column(array_filter($spawns, fn($x) => $x['guid'] > 0 || $x['type'] != Type::NPC), 'guid'))
                $worldPos = WorldPosition::getForGUID(self::$dbType, ...$guids);

        foreach ($spawns as $s)
        {
            $isAccessory = $s['guid'] < 0 && $s['type'] == Type::NPC;

            // check, if we can attach waypoints to creature
            // we will get a nice clusterfuck of dots if we do this for more GUIDs, than we have colors though
            if (!$skipWPs && count($spawns) < 6 && $s['type'] == Type::NPC)
            {
                if ($wPoints = DB::Aowow()->selectAssoc('SELECT * FROM ::creature_waypoints WHERE creatureOrPath = %i AND floor = %i', $s['pathId'] ? -$s['pathId'] : $this->id, $s['floor']))
                {
                    foreach ($wPoints as $i => $p)
                    {
                        $label = [Lang::npc('waypoint').Lang::main('colon').$p['point']];

                        if ($p['wait'])
                            $label[] = Lang::npc('wait').Lang::main('colon').DateTime::formatTimeElapsedFloat($p['wait']);

                        $opts = array(                      // \0 doesn't get printed and tricks Util::toJSON() into handling this as a string .. i feel slightly dirty now
                            'label' => "\0$<br /><span class=\"q0\">".implode('<br />', $label).'</span>',
                            'type'  => $wpIdx
                        );

                        // connective line
                        if ($i > 0 && $wPoints[$i - 1]['areaId'] == $p['areaId'])
                            $opts['lines'] = [[$wPoints[$i - 1]['posX'], $wPoints[$i - 1]['posY']]];

                        $data[$p['areaId']][$p['floor']]['coords'][] = [$p['posX'], $p['posY'], $opts];
                        if (empty($wpSum[$p['areaId']][$p['floor']]))
                            $wpSum[$p['areaId']][$p['floor']] = 1;
                        else
                            $wpSum[$p['areaId']][$p['floor']]++;
                    }
                    $wpIdx++;
                }
            }

            $opts   = $menu = $tt = $info = [];
            $footer = '';

            if ($s['respawn'] > 0)
                $info[1] = '<span class="q0">'.Lang::npc('respawnIn', [Lang::formatTime($s['respawn'] * 1000, 'game', 'timeAbbrev', true)]).'</span>';
            else if ($s['respawn'] < 0)
            {
                $info[1] = '<span class="q0">'.Lang::npc('despawnAfter', [Lang::formatTime(-$s['respawn'] * 1000, 'game', 'timeAbbrev', true)]).'</span>';
                $opts['type'] = 4;                          // make pip purple
            }

            if (!$skipAdmin && User::isInGroup(U_GROUP_STAFF))
            {
                if ($isAccessory)
                    $info[0] = 'Vehicle Accessory';
                else if ($s['guid'] > 0 && ($s['type'] == Type::NPC || $s['type'] == Type::OBJECT))
                    $info[0] = 'GUID'.Lang::main('colon').$s['guid'];

                if ($s['phaseMask'] > 1 && ($s['phaseMask'] & 0xFFFF) != 0xFFFF)
                    $info[2] = Lang::game('phases').Lang::main('colon').Util::asHex($s['phaseMask']);

                if ($s['spawnMask'] == 15)
                    $info[3] = Lang::game('mode').Lang::game('modes', 0, -1);
                else if ($s['spawnMask'])
                    if ($_ = array_intersect_key(Lang::game('modes', $s['mapType']), Util::mask2bits($s['spawnMask'])))
                        $info[4] = Lang::game('mode').implode(', ', $_);

                if ($s['ScriptName'])
                    $info[5] = 'ScriptName'.Lang::main('colon').$s['ScriptName'];
                if ($s['StringId'])
                    $info[6] = 'StringId'.Lang::main('colon').$s['StringId'];

                if ($s['type'] == Type::AREATRIGGER)
                {
                    // teleporter endpoint
                    if ($s['guid'] < 0)
                    {
                        $opts['type'] = 4;
                        $info[7] = 'Teleport Destination';
                    }
                    else
                    {
                        $o = Util::O2Deg($this->orientation);
                        $info[7] = 'Orientation'.Lang::main('colon').$o[0].'° ('.$o[1].')';
                    }
                }

                // guid < 0 are vehicle accessories. those are moved by moving the vehicle
                if (User::isInGroup(U_GROUP_MODERATOR) && $worldPos && !$isAccessory && isset($worldPos[$s['guid']]))
                    $menu = Util::buildPosFixMenu($worldPos[$s['guid']]['mapId'], $worldPos[$s['guid']]['posX'], $worldPos[$s['guid']]['posY'], $s['type'], $s['guid'], $s['areaId'], $s['floor']);

                if ($menu)
                    $footer = '<br /><span class="q2">Click to move pin</span>';
            }

            /* recognized opts
             * url:     string - makes pin clickable
             * tooltip: array  - title => [info: <arr>lines, footer: <string>line]
             * label:   string - single line tooltip (skipped if 'tooltip' is set)
             * menu:    array  - menu definiton (conflicts with url)
             * type:    int    - colors the pip [default, green, red, blue, purple]
             * lines:   array  - [[destX, destY]] - draws line from point to dest
             */

            if ($info)
                $tt['info'] = $info;

            if ($footer)
                $tt['footer'] = $footer;

            if ($tt && $this->getEntry($s['typeId']))
                $opts['tooltip'] = [(string)$this->name => $tt];
            else if ($hasLabel && $this->getEntry($s['typeId']))
                $opts['label'] = $this->name;

            if ($hasLink)
                $opts['url'] = '?' . Type::getFileString(self::$dbType) . '=' . $s['typeId'];

            if ($menu)
                $opts['menu'] = $menu;

            $data[$s['areaId']] [$s['floor']] ['coords'] [] = [$s['posX'], $s['posY'], $opts];
        }

        foreach ($data as $a => &$areas)
            foreach ($areas as $f => &$floor)
                $floor['count'] = count($floor['coords']) - ($wpSum[$a][$f] ?? 0);

        uasort($data, [$this, 'sortBySpawnCount']);
        $this->spawnResult[SPAWNINFO_FULL] = $data;
    }

    private function sortBySpawnCount(array $a, array $b) : int
    {
        $aCount = current($a)['count'];
        $bCount = current($b)['count'];

        return $bCount <=> $aCount;                         // sort descending
    }

    private function createZoneSpawns() : void              // [zoneId1, zoneId2, ..]             for locations-column in listview
    {
        $res = DB::Aowow()->selectCol(
           'SELECT `typeId` AS ARRAY_KEY, GROUP_CONCAT(`areaId` ORDER BY `n` DESC)
            FROM (SELECT `typeId`, `areaId`, COUNT(1) AS "n" FROM ::spawns WHERE `type` = %i AND `typeId` IN %in AND `posX` > 0 AND `posY` > 0 GROUP BY `typeId`, `areaId`) x
            GROUP BY `typeId`',
            self::$dbType, $this->getfoundIDs()
        ) ?: [];

        foreach ($res as &$r)
            $r = explode(',', $r);

        $this->spawnResult[SPAWNINFO_ZONES] = $res;
    }

    // TODO - move to quest endpoint (its only point of use)
    private function createQuestSpawns() : void             // [zoneId => [floor => [[x1, y1], [x2, y2], ..]]]      mapper on quest detail page
    {
        if (self::$dbType == Type::SOUND)
            return;

        $res    = DB::Aowow()->selectAssoc('SELECT `areaId`, `floor`, `typeId`, `posX`, `posY` FROM ::spawns WHERE `type` = %i AND `typeId` IN %in AND `posX` > 0 AND `posY` > 0', self::$dbType, $this->getFoundIDs());
        $spawns = [];
        foreach ($res as $data)
        {
            // zone => floor => spawnData
            // todo (low): why is there a single set of coordinates; which one should be picked, instead of the first? gets used in ShowOnMap.buildTooltip i think
            if (!isset($spawns[$data['areaId']][$data['floor']][$data['typeId']]))
            {
                $spawns[$data['areaId']][$data['floor']][$data['typeId']] = array(
                    'type'          => self::$dbType,
                    'id'            => $data['typeId'],
                    'point'         => '',                      // tbd later (start, end, requirement, sourcestart, sourceend, sourcerequirement)
                    'name'          => Util::localizedString($this->templates[$data['typeId']], 'name'),
                    'coord'         => [$data['posX'], $data['posY']],
                    'coords'        => [[$data['posX'], $data['posY']]],
                    'objective'     => 0,                       // tbd later (1-4 set a color; id of creature this entry gives credit for)
                    'reactalliance' => $this->templates[$data['typeId']]['A'] ?: 0,
                    'reacthorde'    => $this->templates[$data['typeId']]['H'] ?: 0
                );
            }
            else
                $spawns[$data['areaId']][$data['floor']][$data['typeId']]['coords'][] = [$data['posX'], $data['posY']];
        }

        $this->spawnResult[SPAWNINFO_QUEST] = $spawns;
    }

    public function getSpawns(int $mode, bool ...$info) : array|\StdClass
    {
        // only Creatures, GOs and SoundEmitters can be spawned
        if (!self::$dbType || !$this->getFoundIds() || (self::$dbType != Type::NPC && self::$dbType != Type::OBJECT && self::$dbType != Type::SOUND && self::$dbType != Type::AREATRIGGER))
            return [];

        switch ($mode)
        {
            case SPAWNINFO_SHORT:
                if ($this->spawnResult[SPAWNINFO_SHORT] === null)
                    $this->createShortSpawns();

                return $this->spawnResult[SPAWNINFO_SHORT];
            case SPAWNINFO_FULL:
                if (empty($this->spawnResult[SPAWNINFO_FULL]))
                    $this->createFullSpawns(...$info);

                return $this->spawnResult[SPAWNINFO_FULL];
            case SPAWNINFO_ZONES:
                if (empty($this->spawnResult[SPAWNINFO_ZONES]))
                    $this->createZoneSpawns();

                return $this->spawnResult[SPAWNINFO_ZONES][$this->id] ?? [];
            case SPAWNINFO_QUEST:
                if (empty($this->spawnResult[SPAWNINFO_QUEST]))
                    $this->createQuestSpawns();

                return $this->spawnResult[SPAWNINFO_QUEST];
        }

        return [];
    }
}

trait TrProfilerHelper
{
    public static $brickFile = 'profile';                   // profile is multipurpose

    private int $subjectGUID = 0;
    private int $realmId     = 0;
    private int $realmGUID   = 0;

    // sooo subjectGUID cant' be used as $id, because it's not unique across realms <realmId>:<subjectGUID>
    // so we pack them .. assumes PHP_INT_SIZE == 8 / an x64 system
    public function packId() : int
    {
        return ($this->realmId & 0xFFFF) << 40 | ($this->realmGUID & 0xFFFFFFFFFF);
    }

    public function unpackId(int $packedId) : void
    {
        $this->realmId   = ($packedId >> 40) & 0xFFFF;
        $this->realmGUID =  $packedId        & 0xFFFFFFFFFF;
    }

    public static function getRealmDBs(?array $fi) : array
    {
        $dbNames = [];

        foreach(Profiler::getRealms() as $idx => $r)
        {
            if (!empty($fi['sv']) && Profiler::urlize($r['name']) != Profiler::urlize($fi['sv']) && intVal($fi['sv']) != $idx)
                continue;

            if (!empty($fi['rg']) && Profiler::urlize($r['region']) != Profiler::urlize($fi['rg']))
                continue;

            $dbNames[$idx] = 'characters';
        }

        return $dbNames;
    }
}


abstract class DBType
{
    protected array  $templates = [];
    protected array  $curTpl    = [];
    protected int    $matches   = 0;                        // total matches unaffected by sqlLimit in config

    public static   int $dbType;
    public readonly int $id;

    public static int    $contribute = CONTRIBUTE_ANY;
    public static string $dataTable;
    public        bool   $error      = true;

    public const /* string */ QUERY_BASE = '';
    public const /* array */  QUERY_OPTS = [];

    public function __construct(
                  int|array $initData,
        protected array     $extraOpts = [],
        protected bool      $calcTotal = false
    )
    {
        if (is_int($initData))
        {
            $dbQuery = new DBQuery(static::QUERY_BASE, static::QUERY_OPTS, $this->extraOpts, $this->calcTotal);
            if (!$dbQuery->build([['id', $initData]]))
                return;

            foreach ($dbQuery->fetch() as $data)
            {
                $this->applyInitData($data);
                break;                                      // should only ever be one row
            }

            $this->error = false;
            return;
        }

        if ($initData)
        {
            $this->applyInitData($initData);
            $this->error = false;
        }
    }

    // readonly props may only be written like they were private; so force per DBType implementation
    public function applyInitData(array $initData) : void
    {
        $this->id = $initData['id'];
    }

    public static function getName(int $id) : ?LocString
    {
        if (!$id)
            return null;

        if ($n = DB::Aowow()->SelectRow('SELECT `name_loc0`, `name_loc2`, `name_loc3`, `name_loc4`, `name_loc6`, `name_loc8` FROM %n WHERE `id` = %i', static::$dataTable, $id))
            return new LocString($n);
        return null;
    }

    public static function makeLink(int $id, int $fmt = Lang::FMT_HTML, string $cssClass = '') : string
    {
        if ($n = static::getName($id))
            return Lang::makeLink(static::$dbType, $id, $n, $fmt, $cssClass);
        return '';
    }

    /** should return data to extend global js variables for a certain type (e.g. g_items) */
    abstract public function getJSGlobal(int $addMask = GLOBALINFO_ANY) : array;

    /** should return data for a single listview row */
    abstract public function getListviewRow(int $addInfoMask = 0x0) : array;
}

?>
