<?php

namespace Aowow;

if (!defined('AOWOW_REVISION'))
    die("illegal access");


interface ITooltip
{
    public function renderTooltip() : ?string;
}

interface ISource
{
    public function getRawSource(int $src) : array;
    public function getSources() : ?array;
    public function getSourceData(/* int $id = 0 */) : array;
    public function hasAnySource() : bool;
}

/* source more: keys seen used
     'n':   name [always set]
     't':   type [always set]
    'ti':   typeId [always set]
    'bd':   BossDrop [0; 1] [Creature / GO]
    'dd':   DungeonDifficulty [-2: DungeonHC; -1: DungeonNM; 1: Raid10NM; 2:Raid25NM; 3:Raid10HM; 4: Raid25HM; 99: filler trash] [Creature / GO]
     'q':   cssQuality [Items]
     'z':   zone [set when everything happens in one zone]
     'p':   PvP [pvpSourceId]
     's':   Type::TITLE: side; Type::SPELL: skillId (yeah, conflicting use cases. Ain't life just grand.)
     'c':   category [Spells / Quests]
    'c2':   subCat [Quests]
  'icon':   iconString
*/
trait TrSourceHelper
{
    public readonly  array $sources;
    public readonly ?int   $moreType;
    public readonly ?int   $moreTypeId;
    public readonly ?int   $moreZoneId;
    public readonly ?int   $moreMask;                       // srcFlags

    // the result for js
    private ?array $source     = null;
    private ?array $sourceMore = null;

    private function initSources(array $initData) : void
    {
        $src = [];
        for ($i = SRC_CRAFTED; $i < MAX_SOURCES; $i++)
            $src[$i][] = $initData['src'.$i] ?: null;

        $this->sources = $src;
    }

    public function getRawSource(int $src) : array
    {
        return $this->sources[$src] ?? [];
    }

    public function hasAnySource() : bool
    {
        return !!array_filter($this->sources);
    }

    public function prepareSourceMore(?DBType $src = null) : void
    {
        if (!$this->sourceMore !== null || !($this instanceof DBType))
            return;

        // not provided by external bulk operation
        if (!$src && $this->moreType && $this->moreTypeId)
            $src = Type::newType($this->moreType, $this->moreTypeId);

        if ($src && $src instanceof ISource && $src->id == $this->id)
            $this->sourceMore = $src->getSourceData();
        else
            $this->sourceMore = [];
    }

    public function getSources() : ?array
    {
        if (empty($this->sources))
            return null;

        if ($this->sourceMore === null)
            $this->prepareSourceMore();

        $s  = array_keys($this->sources);
        $sm = [];

        if ($_ = $this->sourceMore)
            $sm = $_;

        if ($p = $this->sources[SRC_PVP])
            $sm['p'] = $p[0];

        if ($z = $this->moreZoneId)
            $sm['z'] = $z;

        if ($this->moreMask & SRC_FLAG_BOSSDROP)
            $sm['bd'] = 1;

        if ($this->sources[SRC_DROP])
        {
            /*
                mode        srcFlag     log2    dd Flag
                10N/D-NH    0b0001      0       0b001
                25N/D-HC    0b0010      1       0b010
                10H         0b0100      2       0b011
                25H         0b1000      3       0b100
            */
            if ($this->moreMask & SRC_FLAG_COMMON)
                $sm['dd'] = 99;
            else if ($this->moreMask & SRC_FLAG_DUNGEON_DROP)
                $sm['dd'] = $this->sources[SRC_DROP][0] * -1;
            else if ($this->moreMask & SRC_FLAG_RAID_DROP)
            {
                $dd = log($this->sources[SRC_DROP][0], 2);
                if ($dd == intVal($dd))                     // only one bit set
                    $sm['dd'] = $dd + 1;
            }
        }

        return [$s, $sm ? [$sm] : []];
    }
}

interface IListview
{
    // should return data required to display an arbitrary listview
    public function getListviewData() : array;
    // test if a property is in use
    public function hasSetFields(?string ...$fields) : int;
    // test if a property is in use and different between rows
    public function hasDiffFields(?string ...$fields) : int;
}


/*
    !IMPORTANT!
    It is flat out impossible to distinguish between floors for multi-level areas, if the floors overlap each other!
    The coordinates generated by the script WILL be on every level and will have to be removed MANUALLY!

    impossible := you are not keen on reading wmo data and match it to DungeonMapChunk.dbc;
*/
/** set of spawnpoint related aggregators */
trait TrSpawns
{
    /**
     * for locations-column in listview
     *
     * @param DBTypeSet $set limited to:
     * * `CreatureSet`
     * * `GameobjectSet`
     * @return array [zoneId1, zoneId2, ..] up to three. If more, then `-1` indicates omitted zones
     */
    public static function createZoneSpawns(GameobjectSet|CreatureSet $set) : array
    {
        $result = DB::Aowow()->selectCol(
           'SELECT `typeId` AS ARRAY_KEY, GROUP_CONCAT(`areaId` ORDER BY `n` DESC)
            FROM (SELECT `typeId`, `areaId`, COUNT(1) AS "n" FROM ::spawns WHERE `type` = %i AND `typeId` IN %in AND `posX` > 0 AND `posY` > 0 GROUP BY `typeId`, `areaId`) x
            GROUP BY `typeId`',
            self::$dbType, $set->getfoundIDs()
        ) ?: [];

        foreach ($result as &$r)
            $r = explode(',', $r);

        return $result;
    }

    /**
     * tooltip2 for spawnable entities
     * enabled by <a rel="map" ...> or anchor #map
     * (one area, one floor, one creature, no survivors)
     *
     * @param DBType $entity limited to:
     * * `Creature`
     * * `Gameobject`
     * * `Sound`
     * * `Areatrigger`
     * @return \StdClass [zoneId, floor, [[x1, y1], [x2, y2], ..]]
     */
    public static function createShortSpawns(DBType $entity) : \StdClass
    {
        // first - get zone/floor with the most spawns
        // second - get relevant spawn points
        $result = new \StdClass;

        if ($entity::$dbType == Type::NPC || $entity::$dbType == Type::OBJECT || $entity::$dbType == Type::SOUND || $entity::$dbType == Type::AREATRIGGER)
            if ($res = DB::Aowow()->selectRow('SELECT `areaId`, `floor` FROM ::spawns WHERE `type` = %i AND `typeId` = %i AND `posX` > 0 AND `posY` > 0 GROUP BY `areaId`, `floor` ORDER BY COUNT(1) DESC LIMIT 1', $entity::$dbType, $entity->id))
            {
                $result->zone   = $res['areaId'];
                $result->coords = array(
                    $res['floor'] => DB::Aowow()->selectAssoc('SELECT `posX` AS "0", `posY` AS "1" FROM ::spawns WHERE `type` = %i AND `typeId` = %i AND `areaId` = %i AND `floor` = %i AND `posX` > 0 AND `posY` > 0', $entity::$dbType, $entity->id, $res['areaId'], $res['floor']) ?: []
                );
            }

        return $result;
    }

    /**
     * for display on map on detail page
     * (for historic reasons )
     * @param DBType|DBTypeSet $set limited to:
     * * `Creature` `CreatureSet`
     * * `Gameobject` `GameobjectSet`
     * * `Sound` `SoundSet`
     * * `Areatrigger` `AreatriggerSet`
     * @param bool $skipWPs do not display waypoints
     * @param bool $skipAdmin neither display admin info nor attach spawnposfix menu
     * @param bool $hasLabel use entities name as tooltip if it would otherwise be empty
     * @param bool $hasLink attach link to entity to pip
     * @return array [zoneId => [floor => ['coords' => [[x, y, opts], ...], count => n]]]
     */
    private static function createFullSpawns(DBType|DBTypeSet $set, bool $skipWPs = false, bool $skipAdmin = false, bool $hasLabel = false, bool $hasLink = false) : array
    {
        // works for both Sets and Entities
        if ($set::$dbType != Type::NPC && $set::$dbType != Type::OBJECT && $set::$dbType != Type::SOUND && $set::$dbType != Type::AREATRIGGER)
            return [];

        if ($set instanceof DBType)
        {
            $tmp = $set;
            ($set = Type::newSet($set::$dbType, null))->import($tmp);
            unset($tmp);
        }

        $result   = [];
        $wpSum    = [];                                     // subtract from pip total later to get spawn count
        $wpIdx    = 0;                                      // map pip color
        $worldPos = [];
        $spawns   = DB::Aowow()->selectAssoc(
           'SELECT CASE WHEN z.`type` = %i THEN 1
                        WHEN z.`type` = %i THEN 2
                        WHEN z.`type` = %i THEN 2
                        ELSE 0
                   END AS "mapType",
                   IF (s`pathId`, -s`pathId`, s`typeId`) AS "creatureOrPath"
                   s.*
            FROM   ::spawns s
            JOIN   ::zones z ON s.areaId = z.id
            WHERE s.`type` = %i AND s.`typeId` IN %in AND s.`posX` > 0 AND s.`posY` > 0',
            MAP_TYPE_DUNGEON_HC, MAP_TYPE_MMODE_RAID, MAP_TYPE_MMODE_RAID_HC,
            $set::$dbType, $set->getFoundIDs()
        ) ?: [];

        if (!$skipAdmin && User::isInGroup(U_GROUP_MODERATOR))
            if ($guids = array_column(array_filter($spawns, fn($x) => $x['guid'] > 0 || $x['type'] != Type::NPC), 'guid'))
                $worldPos = WorldPosition::getForGUID($set::$dbType, ...$guids);

        // check, if we can attach waypoints to creature
        // we will get a nice clusterfuck of dots if we do this for more GUIDs, than we have colors though
        $wPoints = [];
        $wpSum   = [];
        if (!$skipWPs && $spawns && count($spawns) < 6 && $set::$dbType == Type::NPC)
            $wPoints = DB::Aowow()->selectAssoc('SELECT cw.`creatureOrPath` AS ARRAY_KEY, cw.`floor` AS ARRAY_KEY2, cw.* FROM ::creature_waypoints cw WHERE cw.`creatureOrPath` = %i AND cw.`floor` = %i', array_column($spawns, 'creatureOrPath'));

        foreach ($spawns as $s)
        {
            $isAccessory = $s['guid'] < 0 && $s['type'] == Type::NPC;

            foreach ($wPoints[$s['creatureOrPath']][$s['floor']] ?? [] as $i => $p)
            {
                $label = [Lang::npc('waypoint').Lang::main('colon').$p['point']];

                if ($p['wait'])
                    $label[] = Lang::npc('wait').Lang::main('colon').DateTime::formatTimeElapsedFloat($p['wait']);

                $opts = array(                              // \0 doesn't get printed and tricks Util::toJSON() into handling this as a string .. i feel slightly dirty now
                    'label' => "\0$<br /><span class=\"q0\">".implode('<br />', $label).'</span>',
                    'type'  => $wpIdx
                );

                // connective line
                if ($i > 0 && $wPoints[$i - 1]['areaId'] == $p['areaId'])
                    $opts['lines'] = [[$wPoints[$i - 1]['posX'], $wPoints[$i - 1]['posY']]];

                $result[$p['areaId']][$p['floor']]['coords'][] = [$p['posX'], $p['posY'], $opts];
                $wpSum[$p['areaId']][$p['floor']] = ($wpSum[$p['areaId']][$p['floor']] ?? 0) + 1;
            }
            $wpIdx++;

            $opts   = $menu = $tt = $info = [];
            $footer = '';

            if ($s['respawn'] > 0)
                $info[1] = '<span class="q0">'.Lang::npc('respawnIn', [Lang::formatTime($s['respawn'] * 1000, 'game', 'timeAbbrev', true)]).'</span>';
            else if ($s['respawn'] < 0)
            {
                $info[1] = '<span class="q0">'.Lang::npc('despawnAfter', [Lang::formatTime(-$s['respawn'] * 1000, 'game', 'timeAbbrev', true)]).'</span>';
                $opts['type'] = 4;                          // make pip purple
            }

            if (!$skipAdmin && User::isInGroup(U_GROUP_STAFF))
            {
                if ($isAccessory)
                    $info[0] = 'Vehicle Accessory';
                else if ($s['guid'] > 0 && ($s['type'] == Type::NPC || $s['type'] == Type::OBJECT))
                    $info[0] = 'GUID'.Lang::main('colon').$s['guid'];

                if ($s['phaseMask'] > 1 && ($s['phaseMask'] & 0xFFFF) != 0xFFFF)
                    $info[2] = Lang::game('phases').Lang::main('colon').Util::asHex($s['phaseMask']);

                if ($s['spawnMask'] == 15)
                    $info[3] = Lang::game('mode').Lang::game('modes', 0, -1);
                else if ($s['spawnMask'])
                    if ($_ = array_intersect_key(Lang::game('modes', $s['mapType']), Util::mask2bits($s['spawnMask'])))
                        $info[4] = Lang::game('mode').implode(', ', $_);

                if ($s['ScriptName'])
                    $info[5] = 'ScriptName'.Lang::main('colon').$s['ScriptName'];
                if ($s['StringId'])
                    $info[6] = 'StringId'.Lang::main('colon').$s['StringId'];

                // teleporter endpoint
                if ($s['type'] == Type::AREATRIGGER && $s['guid'] < 0)
                {
                    $opts['type'] = 4;
                    $info[7] = 'Teleport Destination';
                }
                /* can no longer access $this .. also mostly useless, so away it goes
                 *
                 * [$num, $word] = Util::O2Deg($this->orientation);
                 * $info[7] = 'Orientation'.Lang::main('colon').$num.'° ('.$word.')';
                 */

                // guid < 0 are vehicle accessories. those are moved by moving the vehicle
                if (User::isInGroup(U_GROUP_MODERATOR) && $worldPos && !$isAccessory && isset($worldPos[$s['guid']]))
                    $menu = Util::buildPosFixMenu($worldPos[$s['guid']]['mapId'], $worldPos[$s['guid']]['posX'], $worldPos[$s['guid']]['posY'], $s['type'], $s['guid'], $s['areaId'], $s['floor']);

                if ($menu)
                    $footer = '<br /><span class="q2">Click to move pin</span>';
            }

            /* recognized opts
             * url:     string - makes pin clickable
             * tooltip: array  - title => [info: <arr>lines, footer: <string>line]
             * label:   string - single line tooltip (skipped if 'tooltip' is set)
             * menu:    array  - menu definiton (conflicts with url)
             * type:    int    - colors the pip [default, green, red, blue, purple]
             * lines:   array  - [[destX, destY]] - draws line from point to dest
             */

            if ($info)
                $tt['info'] = $info;

            if ($footer)
                $tt['footer'] = $footer;

            /** @var Creature|Gameobject|Sound|Areatrigger $entry */
            if ($entry = $set->getEntry($s['typeId']))
            {
                if ($tt)
                    $opts['tooltip'] = [(string)$entry->name => $tt];
                else if ($hasLabel)
                    $opts['label'] = $entry->name;
            }

            if ($hasLink)
                $opts['url'] = '?' . Type::getFileString($set::$dbType) . '=' . $s['typeId'];

            if ($menu)
                $opts['menu'] = $menu;

            $result[$s['areaId']] [$s['floor']] ['coords'] [] = [$s['posX'], $s['posY'], $opts];
        }

        foreach ($result as $a => &$areas)
            foreach ($areas as $f => &$floor)
                $floor['count'] = count($floor['coords']) - ($wpSum[$a][$f] ?? 0);

        uasort($result, self::sortBySpawnCount(...));

        return $result;
    }

    private static function sortBySpawnCount(array $a, array $b) : int
    {
        $aCount = current($a)['count'];
        $bCount = current($b)['count'];

        return $bCount <=> $aCount;                         // sort descending
    }
}

trait TrProfilerHelper
{
    public static $brickFile = 'profile';                   // profile is multipurpose

    private int $subjectGUID = 0;
    private int $realmId     = 0;
    private int $realmGUID   = 0;

    // sooo subjectGUID cant' be used as $id, because it's not unique across realms <realmId>:<subjectGUID>
    // so we pack them .. assumes PHP_INT_SIZE == 8 / an x64 system
    public function packId() : int
    {
        return ($this->realmId & 0xFFFF) << 40 | ($this->realmGUID & 0xFFFFFFFFFF);
    }

    public function unpackId(int $packedId) : void
    {
        $this->realmId   = ($packedId >> 40) & 0xFFFF;
        $this->realmGUID =  $packedId        & 0xFFFFFFFFFF;
    }

    public static function getRealmDBs(?array $fi) : array
    {
        $dbNames = [];

        foreach(Profiler::getRealms() as $idx => $r)
        {
            if (!empty($fi['sv']) && Profiler::urlize($r['name']) != Profiler::urlize($fi['sv']) && intVal($fi['sv']) != $idx)
                continue;

            if (!empty($fi['rg']) && Profiler::urlize($r['region']) != Profiler::urlize($fi['rg']))
                continue;

            $dbNames[$idx] = 'characters';
        }

        return $dbNames;
    }
}


abstract class DBType
{
    protected array  $templates = [];
    protected array  $curTpl    = [];
    protected int    $matches   = 0;                        // total matches unaffected by sqlLimit in config

    public static   int $dbType;
    public readonly int $id;

    public static int    $contribute = CONTRIBUTE_ANY;
    public static string $dataTable;
    public        bool   $error      = true;

    public const /* string */ QUERY_BASE = '';
    public const /* array */  QUERY_OPTS = [];

    public function __construct(
                  int|array $initData,
        protected array     $extraOpts = [],
        protected bool      $calcTotal = false
    )
    {
        if (is_int($initData))
        {
            $dbQuery = new DBQuery(static::QUERY_BASE, static::QUERY_OPTS, $this->extraOpts, $this->calcTotal);
            if (!$dbQuery->build([['id', $initData]]))
                return;

            foreach ($dbQuery->fetch() as $data)
            {
                $this->applyInitData($data);
                break;                                      // should only ever be one row
            }

            $this->error = false;
            return;
        }

        if ($initData)
        {
            $this->applyInitData($initData);
            $this->error = false;
        }
    }

    // readonly props may only be written like they were private; so force per DBType implementation
    public function applyInitData(array $initData) : void
    {
        $this->id = $initData['id'];
    }

    public static function getName(int $id) : ?LocString
    {
        if (!$id)
            return null;

        if ($n = DB::Aowow()->SelectRow('SELECT `name_loc0`, `name_loc2`, `name_loc3`, `name_loc4`, `name_loc6`, `name_loc8` FROM %n WHERE `id` = %i', static::$dataTable, $id))
            return new LocString($n);
        return null;
    }

    public static function makeLink(int $id, int $fmt = Lang::FMT_HTML, string $cssClass = '') : string
    {
        if ($n = static::getName($id))
            return Lang::makeLink(static::$dbType, $id, $n, $fmt, $cssClass);
        return '';
    }

    /** should return data to extend global js variables for a certain type (e.g. g_items) */
    abstract public function getJSGlobal(int $addMask = GLOBALINFO_ANY) : array;

    /** should return data for a single listview row */
    abstract public function getListviewRow(int $addInfoMask = 0x0) : array;
}

?>
