ALTER TABLE `aowow_itemset`
    DROP COLUMN `bonusParsed`;

DROP TABLE IF EXISTS `aowow_item_stats`;
CREATE TABLE `aowow_item_stats` (
  `type` smallint(5) unsigned NOT NULL,
  `typeId` mediumint(8) NOT NULL,
  `nsockets` tinyint(3) unsigned NULL,
  `dps` float(8,2) NULL,
  `damagetype` tinyint(4) NULL,
  `dmgmin1` mediumint(5) unsigned NULL,
  `dmgmax1` mediumint(5) unsigned NULL,
  `speed` float(8,2) NULL,
  `mledps` float(8,2) NULL,
  `mledmgmin` mediumint(5) unsigned NULL,
  `mledmgmax` mediumint(5) unsigned NULL,
  `mlespeed` float(8,2) NULL,
  `rgddps` float(8,2) NULL,
  `rgddmgmin` mediumint(5) unsigned NULL,
  `rgddmgmax` mediumint(5) unsigned NULL,
  `rgdspeed` float(8,2) NULL,
  `dmg` float(8,2) NULL,
  `mana` mediumint(6) NULL,
  `health` mediumint(6) NULL,
  `agi` mediumint(6) NULL,
  `str` mediumint(6) NULL,
  `int` mediumint(6) NULL,
  `spi` mediumint(6) NULL,
  `sta` mediumint(6) NULL,
  `energy` mediumint(6) NULL,
  `rage` mediumint(6) NULL,
  `focus` mediumint(6) NULL,
  `runic` mediumint(6) NULL,
  `defrtng` mediumint(6) NULL,
  `dodgertng` mediumint(6) NULL,
  `parryrtng` mediumint(6) NULL,
  `blockrtng` mediumint(6) NULL,
  `mlehitrtng` mediumint(6) NULL,
  `rgdhitrtng` mediumint(6) NULL,
  `splhitrtng` mediumint(6) NULL,
  `mlecritstrkrtng` mediumint(6) NULL,
  `rgdcritstrkrtng` mediumint(6) NULL,
  `splcritstrkrtng` mediumint(6) NULL,
  `_mlehitrtng` mediumint(6) NULL,
  `_rgdhitrtng` mediumint(6) NULL,
  `_splhitrtng` mediumint(6) NULL,
  `_mlecritstrkrtng` mediumint(6) NULL,
  `_rgdcritstrkrtng` mediumint(6) NULL,
  `_splcritstrkrtng` mediumint(6) NULL,
  `mlehastertng` mediumint(6) NULL,
  `rgdhastertng` mediumint(6) NULL,
  `splhastertng` mediumint(6) NULL,
  `hitrtng` mediumint(6) NULL,
  `critstrkrtng` mediumint(6) NULL,
  `_hitrtng` mediumint(6) NULL,
  `_critstrkrtng` mediumint(6) NULL,
  `resirtng` mediumint(6) NULL,
  `hastertng` mediumint(6) NULL,
  `exprtng` mediumint(6) NULL,
  `atkpwr` mediumint(6) NULL,
  `mleatkpwr` mediumint(6) NULL,
  `rgdatkpwr` mediumint(6) NULL,
  `feratkpwr` mediumint(6) NULL,
  `splheal` mediumint(6) NULL,
  `spldmg` mediumint(6) NULL,
  `manargn` mediumint(6) NULL,
  `armorpenrtng` mediumint(6) NULL,
  `splpwr` mediumint(6) NULL,
  `healthrgn` mediumint(6) NULL,
  `splpen` mediumint(6) NULL,
  `block` mediumint(6) NULL,
  `mastrtng` mediumint(6) NULL,
  `armor` mediumint(6) NULL,
  `armorbonus` mediumint(6) NULL,
  `firres` mediumint(6) NULL,
  `frores` mediumint(6) NULL,
  `holres` mediumint(6) NULL,
  `shares` mediumint(6) NULL,
  `natres` mediumint(6) NULL,
  `arcres` mediumint(6) NULL,
  `firsplpwr` mediumint(6) NULL,
  `frosplpwr` mediumint(6) NULL,
  `holsplpwr` mediumint(6) NULL,
  `shasplpwr` mediumint(6) NULL,
  `natsplpwr` mediumint(6) NULL,
  `arcsplpwr` mediumint(6) NULL,
  PRIMARY KEY (`type`,`typeId`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

UPDATE `aowow_dbversion`
    SET `sql` = CONCAT(IFNULL(`sql`, ''), ' item_stats');
