cO(LANG, {
	tc_rank: "Rank $1/$2",
	tc_tier: "Requires $1 points in $2 Talents",
	tc_prereq: "Requires $1 point in $2",
	tc_prereqpl: "Requires $1 points in $2",
	tc_learn: "Click to learn",
	tc_unlearn: "Right-click to unlearn",
	tc_unlearn2: "Shift-click to unlearn",
	tc_nextrank: "Next rank:",
	tc_inccap: "Click to increase to 80",
	tc_deccap: "Click to decrease to 70",
	tc_addbon: "Click to add 4 bonus points from<br />the Beast Mastery talent",
	tc_rembon: "Click to remove the bonus<br />points from Beast Mastery",
	tc_point: "point",
	tc_points: "Points",
	tc_none: "None",
	tc_printh: "Level $1 $2",
	tc_link: "Link to this build",
	tc_resetall: "Reset all",
	tc_resettree: "Reset tree",
	tc_resetglyphs: "Reset glyphs",
	tc_lock: "Lock",
	tc_unlock: "Unlock",
	tc_reset: "reset",
	tc_ptsleft: "Points left: ",
	tc_ptsspent: "Points spent: ",
	tc_reqlevel: "Required level: ",
	tc_levelcap: "Level cap: ",
	tc_bonuspts: "Bonus points: ",
	tc_help: "Help",
	tc_import: "Import",
	tc_summary: "Summary",
	tc_restore: "Restore",
	tc_export: "Export",
	tc_link: "Link",
	tc_print: "Print",
	tc_glyphs: "Glyphs",
	tc_empty: "Empty",
	tc_locked: "Locked",
	tc_majgly: "Major Glyph",
	tc_mingly: "Minor Glyph",
	tc_lockgly: "Unlocked at level $1",
	tc_addgly: "Click to inscribe your spellbook",
	tc_remgly: "Right-click to remove",
	tc_remgly2: "Shift-click to remove",
	tc_nonegly: "None",
   	tc_glyphnote: "Some glyphs were filtered out due to the specified level restriction.",
	tc_viewtalents: "View Talent Trees",
	tc_viewsummary: "View Summaries",
    tc_level: "Level %s",
	alert_invalidurl: "Invalid URL.",
	alert_chooseclass: "Please choose a class first.",
	alert_choosefamily: "Please choose a pet family first.",
	alert_buildempty: "Your build is empty.",
	prompt_importwh: "Please paste the URL of a build made with Wowhead's talent calculator:",
	prompt_importblizz: "Please paste the URL of a build made with Blizzard's talent calculator:"
});