/*
 TalentCalc_frfr.js version 294 (27.07.2009)
*/
cO(LANG, {
	tc_rank: "Rang $1/$2",
	tc_tier: "Requiert $1 points en $2",
	tc_prereq: "Requiert $1 point en $2",
	tc_prereqpl: "Requiert $1 points en $2",
	tc_learn: "Cliquer pour apprendre",
	tc_unlearn: "Clic droit pour desapprendre",
	tc_unlearn2: "Maj-clic pour desapprendre",
	tc_nextrank: "Prochain rang :",
	tc_inccap: "Cliquer pour augmenter a 80",
	tc_deccap: "Cliquer pour diminuer a 70",
	tc_addbon: "Cliquer pour ajouter 4 points bonis<br />du talent Maitrise des betes",
	tc_rembon: "Cliquer pour enlever les points bonis<br /> de Maitrise des betes",
	tc_point: "point",
	tc_points: "points",
	tc_none: "Aucun",
	tc_printh: "$2 de niveau $1",
	tc_link: "Lien",
	tc_resetall: "Tout effacer",
	tc_lock: "Verrouiller",
	tc_unlock: "Deverrouiller",
	tc_reset: "effacer",
	tc_ptsleft: "Points restants : ",
	tc_ptsspent: "Points utilises : ",
	tc_reqlevel: "Niveau requis : ",
	tc_levelcap: "Niveau maximum : ",
	tc_bonuspts: "Points bonis : ",
	tc_help: "Aide",
	tc_import: "Importer",
	tc_summary: "Resume",
	tc_restore: "Restaurer",
	tc_export: "Exporter",
	tc_glyphs: "Glyphes",
	tc_empty: "Vide",
	tc_majgly: "Glyphe majeur",
	tc_mingly: "Glyphe mineur",
	tc_addgly: "Cliquer pour calligraphier votre grimoire",
	tc_remgly: "Clic droit pour enlever",
	tc_remgly2: "Maj-click pour enlever",
	tc_nonegly: "Aucun",
   	tc_glyphnote: "Certains glyphes ont été filtrés à cause de la restriction de niveau.",
	tc_level: "Niveau %s",
	alert_invalidurl: "URL invalide.",
	alert_chooseclass: "Veuillez d'abord selectionner une classe.",
	alert_choosefamily: "Veuillez d'abord selectionner une famille de familier.",
	alert_buildempty: "Votre template est vide.",
	prompt_importwh: "Veuillez coller l'URL d'un template fait avec le calculateur de talents de Wowhead :",
	prompt_importblizz: "Veuillez coller l'URL d'un template fait avec le calculateur de talents de Blizzard :"
});