cO(LANG, {
	tc_rank: "Rango $1/$2",
	tc_tier: "Necesita $1 puntos en talentos de $2",
	tc_prereq: "Necesita $1 punto en $2",
	tc_prereqpl: "Necesita $1 puntos en $2",
	tc_learn: "Has click para aprender esto",
	tc_unlearn: "Click derecho para olvidar",
	tc_unlearn2: "Shift-click para olvidar",
	tc_nextrank: "Siguiente rango:",
	tc_inccap: "Click para subir a 80",
	tc_deccap: "Click para bajar a 70",
	tc_addbon: "Click to add 4 bonus points from<br />the Beast Mastery talent",
	tc_rembon: "Click to remove the bonus<br />points from Beast Mastery",
	tc_point: "punto",
	tc_points: "puntos",
	tc_none: "Ninguno",
	tc_printh: "Nivel $1 $2",
	tc_link: "Enlazar estos talebtos",
	tc_resetall: "Reiniciar todos",
	tc_lock: "Bloquear",
	tc_unlock: "Desbloquear",
	tc_reset: "reiniciar",
	tc_ptsleft: "Puntos restantes: ",
	tc_ptsspent: "Puntos utilizados: ",
	tc_reqlevel: "Nivel requerido: ",
	tc_levelcap: "Nivel máximo: ",
	tc_bonuspts: "Bonus points: ",
	tc_help: "Ayuda",
	tc_import: "Importar",
	tc_summary: "Imprimir",
	tc_restore: "Restaurar",
	tc_export: "Exportar",
	tc_glyphs: "Glifos",
	tc_empty: "Vacio",
	tc_majgly: "Glifo sublime",
	tc_mingly: "Glifo menor",
	tc_addgly: "Click para inscribirlo en tu libro de hechizos",
	tc_remgly: "Click derecho para quitar",
	tc_remgly2: "Shift-click para quitar",
	tc_nonegly: "Ninguno",
   	tc_glyphnote: "Algunos glifos han sido filrtrados debido a requisitos de niveles.",
    tc_level: "Nivel %s",
	alert_invalidurl: "Enlace no valido.",
	alert_chooseclass: "Por favor selecciona una clase primero.",
	alert_choosefamily: "Please choose a pet family first.",
	alert_buildempty: "Your build is empty.",
	prompt_importwh: "Please paste the URL of a build made with Wowhead's talent calculator:",
	prompt_importblizz: "Please paste the URL of a build made with Blizzard's talent calculator:"
});