cO(LANG, {
	tc_rank: "Rang $1/$2",
	tc_tier: "Benötigt $1 Punkte bei $2-Talenten",
	tc_prereq: "Benötigt $1 Punkt in $2",
	tc_prereqpl: "Benötigt $1 Punkte in $2",
	tc_learn: "Zum Erlernen hier klicken",
	tc_unlearn: "Rechtsklick zum Verlernen",
	tc_unlearn2: "Shift-Klick zum Verlernen",
	tc_nextrank: "Nächster Rang: ",
	tc_inccap: "Klicken, um auf 80 zu erhöhen",
	tc_deccap: "Klicken, um auf 70 zu verringern",
	tc_addbon: "Klicken, um 4 Extrapunkte durch<br />das Talent 'Herr der Tiere' hinzuzufügen",
	tc_rembon: "Klicken, um die Extrapunkte<br />durch 'Herr der Tiere' zu entfernen",
	tc_point: "Punkt",
	tc_points: "Punkte",
	tc_none: "Keine",
	tc_printh: "Stufe $1 $2",
	tc_link: "Link",
	tc_resetall: "Alle löschen",
	tc_resettree: "Baum zurücksetzen",
	tc_resetglyphs: "Glyphen zurücksetzen",
	tc_lock: "Sperren",
	tc_unlock: "Entsperren",
	tc_reset: "löschen",
	tc_ptsleft: "Verbleibende Punkte: ",
	tc_ptsspent: "Vergebene Punkte: ",
	tc_reqlevel: "Benötigte Stufe: ",
	tc_levelcap: "Stufenbeschränkung: ",
	tc_bonuspts: "Bonuspunkte: ",
	tc_help: "Hilfe",
	tc_import: "Importieren",
	tc_summary: "Zusammenfassung",
	tc_restore: "Wiederherstellen",
	tc_export: "Exportieren",
	tc_link: "Link",
	tc_print: "Drucken",
	tc_glyphs: "Glyphen",
	tc_empty: "Leer",
	tc_locked: "Verschlossen",
	tc_majgly: "Erhebliche Glyphe",
	tc_mingly: "Geringe Glyphe",
	tc_lockgly: "Freigegeben auf Stufe $1",
	tc_addgly: "Zum Einschreiben eurer Zauber rechtsklicken",
	tc_remgly: "Zum Entfernen rechtsklicken",
	tc_remgly2: "Zum Entfernen Shift-Klick",
	tc_nonegly: "Keine",
  	tc_glyphnote: "Einige Glyphen wurden wegen der festgesetzten Stufenbegrenzung ausgefiltert.",
	tc_viewtalents: "Talentbäume anzeigen",
	tc_viewsummary: "Zusammenfassungen anzeigen",
    tc_level: "Stufe %s",
	alert_invalidurl: "Ungültige URL.",
	alert_chooseclass: "Bitte wählt zunächst eine Klasse aus.",
	alert_choosefamily: "Bitte wählt zunächst eine Tierart aus.",
	alert_buildempty: "Ihr habt noch keine Talentpunkte verteilt.",
	prompt_importwh: "Bitte gebt die URL einer Talentverteilung ein, die mit dem Talentrechner von Wowhead erstellt wurde: ",
	prompt_importblizz: "Bitte gebt die URL einer Talentverteilung ein, die mit dem Talentrechner von Blizzard erstellt wurde: "
});
